# Generated by Django 6.0 on 2025-12-20 15:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1ID', models.BigIntegerField()),
                ('player2ID', models.BigIntegerField()),
                ('match_date', models.DateField(default=datetime.date(2025, 1, 1))),
                ('player1WinOdds', models.DecimalField(decimal_places=2, max_digits=20)),
                ('player2WinOdds', models.DecimalField(decimal_places=2, max_digits=20)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
