# Generated by Django 6.0 on 2025-12-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='playerID',
            new_name='player_id',
        ),
        migrations.RenameField(
            model_name='predictions',
            old_name='player1ID',
            new_name='player1_id',
        ),
        migrations.RenameField(
            model_name='predictions',
            old_name='player2ID',
            new_name='player2_id',
        ),
    ]
