# Generated by Django 6.0 on 2026-01-17 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_predictions_player2winoddsrforest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionsGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_id', models.BigIntegerField()),
                ('player2_id', models.BigIntegerField()),
                ('match_date', models.DateField(default=datetime.date(2025, 1, 1))),
                ('player1WinOddsLogistic', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('player2WinOddsLogistic', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('player1WinOddsRForest', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('player2WinOddsRForest', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('player1WinOddsDTree', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('player2WinOddsDTree', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
